# Generated by Django 3.2.18 on 2023-02-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Task'},
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='slug',
        ),
    ]
