# Generated by Django 3.2.18 on 2023-02-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('to-do', 'To do'), ('in-progress', 'In progress'), ('done', 'Done')], default='to-do', max_length=12),
        ),
    ]
