# Generated by Django 3.2.18 on 2023-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('to-do', 'to-do'), ('in-progress', 'in-progress'), ('done', 'done')], max_length=12),
        ),
    ]
