# Generated by Django 3.2.18 on 2023-02-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tasks_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='completed_at',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Publish')], default=1, max_length=12),
        ),
    ]
