# Generated by Django 3.2.18 on 2023-02-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(choices=[('to-do', 'Draft'), ('publish', 'Publish')], default=0),
        ),
    ]
